import pytest
from fastapi.testclient import TestClient
import numpy as np
import pandas as pd
import os
import sys
import json

# Add parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app.server import app, data_manager
from pipeline.solve_user_taste import solve_user_taste

@pytest.fixture
def client():
    # Ensure data is loaded
    if data_manager.metadata is None:
        data_manager.load_data()
    return TestClient(app)

@pytest.mark.skip(reason="Skipping until Recommender is overhauled to match new Kernel-based Solver")
def test_ordinal_parity_user_profile(client):
    """
    Test that the top recommendations generated by the solver (pipeline/solve_user_taste.py)
    perfectly match the recommendations generated by the API (app/server.py)
    when using the same weights and vectors.
    """
    steam_id = "76561198039155404"
    gt_path = f"data/user_{steam_id}_ground_truth.csv"
    
    if not os.path.exists(gt_path):
        pytest.skip(f"Ground truth file not found for {steam_id}, skipping parity test.")

    print(f"\nRunning solver for {steam_id}...")
    # 1. Run Solver to get 'official' recommendations and weights
    # We don't provide an output_path to avoid overwriting production files
    solver_results = solve_user_taste(gt_path, output_path=None)
    
    solver_top_30 = solver_results['top_recommendations']
    solver_weights = solver_results['metadata']
    vibe_vector = solver_results['vibe_vector']
    semantic_vibe_vector = solver_results['semantic_vibe_vector']
    topic_vibe_vector = solver_results.get('topic_vibe_vector')
    
    # 2. Extract top 10 AppIDs from solver
    solver_top_ids = [r['appid'] for r in solver_top_30[:10]]
    print(f"Solver Top 10: {solver_top_ids}")

    # 3. Construct API Request using Solver's exported parameters
    # Sliders now carry the ABSOLUTE weights (Transparency Mode).
    payload = {
        "alpha": solver_weights.get('semantic', 1.0),
        "beta": solver_weights.get('tag_match', 1.0),
        "gamma_topic": solver_weights.get('topic_match', 0.0),
        "quality_pref": solver_weights.get('quality', 1.0),
        "age_pref": solver_weights.get('age', 1.0),
        "pop_pref": solver_weights.get('popularity', 1.0),
        "disc_pref": solver_results['metadata'].get('discovery', 0.0),
        "length_pref": solver_results['metadata'].get('length', 1.0),
        "difficulty_pref": solver_results['metadata'].get('difficulty', 1.0),
        "price_pref": solver_results['metadata'].get('price', 1.0),
        "top_k": 30,
        "vibe_vector": vibe_vector,
        "semantic_vibe_vector": semantic_vibe_vector,
        "topic_vibe_vector": topic_vibe_vector,
        "metadata_weights": solver_weights,
        "intercept": solver_results['intercept'],
                    "scaling_factor": solver_results['scaling_factor'],
                    "profile_filter": "completed", # Solver excludes only completed games in preview
                    "library_appids": solver_results['library_appids'],
        
        "rated_appids": solver_results['rated_appids'],
        "library_details": solver_results.get('library_details', {}),
        # Default filters used by solver
        "english_only": True,
        "remove_vr": True,
        "remove_utilities": True,
        "remove_unreleased": True,
        "remove_delisted": True
    }

    print("Requesting API recommendations...")
    response = client.post("/recommend", json=payload)
    assert response.status_code == 200
    api_results = response.json()
    
    api_top_ids = [r['appid'] for r in api_results[:10]]
    api_top_percents = [r['match_percent'] for r in api_results[:10]]
    api_top_scores = [r['weighted_score'] for r in api_results[:10]]
    print(f"API Top 10:    {api_top_ids}")
    print(f"API Top Score: {[f'{s:.2f}' for s in api_top_scores]}")
    print(f"API Top %:     {[f'{p:.1f}%' for p in api_top_percents]}")

    # 4. Compare results
    # We check for exact ordinal parity in the top 10
    for i in range(10):
        assert solver_top_ids[i] == api_top_ids[i], f"Ordinal mismatch at rank {i+1}: Solver={solver_top_ids[i]}, API={api_top_ids[i]}"

    # 5. Check for '82% Bug'
    # For a high-fidelity user profile, the top recommendations should NOT all be 82%.
    # They should reflect the user's specific boosted affinity.
    avg_top_percent = np.mean(api_top_percents)
    assert avg_top_percent > 85.0, f"Match percentages are too low (Avg={avg_top_percent:.1f}%). Possible scaling regression."

    print(f"Success: Perfect ordinal parity achieved. Top Avg Match: {avg_top_percent:.1f}%")

@pytest.mark.skip(reason="Skipping until Recommender is overhauled to match new Kernel-based Solver")
def test_ordinal_parity_detects_mismatch(client):
    """
    Negative test: verify that if we send the WRONG multipliers (the squaring bug),
    the ordinal order DOES change, proving the test is sensitive to logic changes.
    """
    steam_id = "76561198039155404"
    gt_path = f"data/user_{steam_id}_ground_truth.csv"
    if not os.path.exists(gt_path):
        pytest.skip(f"Ground truth file not found for {steam_id}")

    solver_results = solve_user_taste(gt_path, output_path=None)
    solver_top_ids = [r['appid'] for r in solver_results['top_recommendations'][:10]]
    solver_weights = solver_results['metadata']

    # SIMULATE A MISMATCH: Set sliders to 1.0 (Neutral) instead of solved weights
    # In Transparency Mode, 1.0 is no longer the correct setting for a solved profile.
    payload = {
        "alpha": 1.0, 
        "beta": 1.0,
        "quality_pref": 1.0,
        "age_pref": 1.0,
        "pop_pref": 1.0,
        "disc_pref": 0.0,
        "length_pref": 1.0,
        "difficulty_pref": 1.0,
        "price_pref": 1.0,
        "top_k": 30,
        "vibe_vector": solver_results['vibe_vector'],
        "semantic_vibe_vector": solver_results['semantic_vibe_vector'],
        "metadata_weights": solver_weights,
        "intercept": solver_results['intercept'],
        "scaling_factor": solver_results['scaling_factor'],
        "profile_filter": "all",
        "library_appids": solver_results['library_appids'],
        "rated_appids": solver_results['rated_appids']
    }

    response = client.post("/recommend", json=payload)
    api_results = response.json()
    api_top_ids = [r['appid'] for r in api_results[:10]]

    # Check if there's any mismatch in the top 10
    has_mismatch = any(s != a for s, a in zip(solver_top_ids, api_top_ids))
    
    print(f"Bugged API Top 10: {api_top_ids}")
    assert has_mismatch, "The test failed to detect an ordinal mismatch when weights were squared! Test sensitivity issue."
    print("Success: Test correctly identified that squaring weights changes recommendation order.")

if __name__ == "__main__":
    # Allow running this test script directly for debugging
    pytest.main([__file__, "-s"])
